import { Prisma } from "@prisma/client";

export const users: Prisma.UserCreateManyInput[] = [{
  id: 1,
  accountType: 'EMAIL',
  email: 'superadmin@gmail.com',
  contactEmail: 'superadmin@gmail.com',
  password: 'admin123',
  displayName: 'Bapak Admin',
  avatarUrl: 'http://example.com/avatar.jpg',
  role: 'SUPER_ADMIN',
  status: 'ACTIVE',
  referralCode: 'REF123',
},
{
  id: 2,
  accountType: 'EMAIL',
  email: 'storeadmin@gmail.com',
  contactEmail: 'storeadmin@gmail.com',
  password: 'admin123',
  displayName: 'Ibu Admin Store',
  avatarUrl: 'http://example.com/avatar.jpg',
  role: 'STORE_ADMIN',
  status: 'ACTIVE',
  referralCode: 'REF456',
},
{
  id: 3,
  accountType: 'EMAIL',
  email: 'budi@gmail.com',
  contactEmail: 'budi@gmail.com',
  password: 'admin123',
  displayName: 'Budiman',
  avatarUrl: 'http://example.com/avatar.jpg',
  role: 'USER',
  status: 'ACTIVE',
  referralCode: 'REF789',
},
{
  id: 4,
  accountType: 'EMAIL',
  email: 'juliussiregar1011@gmail.com',
  contactEmail: 'juliussiregar1011@gmail.com',
  password: 'admin123',
  displayName: 'Julius Siregar',
  avatarUrl: 'http://example.com/avatar.jpg',
  role: 'STORE_ADMIN',
  status: 'ACTIVE',
  referralCode: 'JUL123',
},
{
  id: 5,
  accountType: 'EMAIL',
  email: 'designwithme21@gmail.com',
  contactEmail: 'designwithme21@gmail.com',
  password: 'admin123',
  displayName: 'Rayhan Hanif',
  avatarUrl: 'http://example.com/avatar.jpg',
  role: 'STORE_ADMIN',
  status: 'ACTIVE',
  referralCode: 'RAY123',
},
{
  id: 6,
  accountType: 'EMAIL',
  email: 'nadirra2000@gmail.com',
  contactEmail: 'nadirra2000@gmail.com',
  password: 'admin123',
  displayName: 'Nadira Safira',
  avatarUrl: 'http://example.com/avatar.jpg',
  role: 'STORE_ADMIN',
  status: 'ACTIVE',
  referralCode: 'NAD123',
}
];
